### ISSUE TITLE
JikesPG grammar syntax support tool  has pubulish.

### ISSUE THREAD

**Issue by kuafuwang** [eclipse/aspectj.eclipse.jdt.core#15]
Here is  a [jdt.core example](https://github.com/kuafuwang/LPG2-grammars-example/tree/main/jdt.core).
It's base on JikesPG 2 grammar.   Generate parser with [LPG grammar syntax support  vscode extion](https://marketplace.visualstudio.com/items?itemName=kuafuwang.lpg-vscode).
The grammar file  in  aspectj.eclipse.jdt.core is base on JikesPG 1.3 . I think you can try  JikesPG 2.0 .

**Comment by kriegaex** [comment]
FYI, AspectJ is a JDT Core fork. For each release, we merge in the upstream grammar. Therefore, we depend on whatever syntax JDT Core uses. We are going to migrate no earlier than the upstream project.

Somehow, your post looks like nothing else than an advertisement for your VS Code extension. Please refrain from opening issues for something like that, you will not make many new friends like that.

@aclement, I think this can be closed and should not be assigned to any milestone. We do not want it in the next release notes.

**Comment by kuafuwang** [comment]
> FYI, AspectJ is a JDT Core fork. For each release, we merge in the upstream grammar. Therefore, we depend on whatever syntax JDT Core uses. We are going to migrate no earlier than the upstream project.
> 
> Somehow, your post looks like nothing else than an advertisement for your VS Code extension. Please refrain from opening issues for something like that, you will not make many new friends like that.
> 
> @aclement, I think this can be closed and should not be assigned to any milestone. We do not want it in the next release notes.

I am sorry.
