### ISSUE TITLE
Typo in FORMATTER_PARENTHESES_POSITIONS_IN_METHOD_DECLARATION

### ISSUE THREAD

**Issue by figsoda** [eclipse/aspectj.eclipse.jdt.core#26]
It should be `declaration` instead of `delcaration`
https://github.com/eclipse/aspectj.eclipse.jdt.core/blob/37759146f8c5e68e69b19258bc31a8c812e8afb7/org.eclipse.jdt.core/formatter/org/eclipse/jdt/core/formatter/DefaultCodeFormatterConstants.java#L1141

not sure if this is the right place to open the issue, please redirect me to the right place if otherwise

**Comment by kriegaex** [comment]
The right place would be [Eclipse JDT Core](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/8cef31cb52c4fc45ae516e9d10c2dfebac6af7bd/org.eclipse.jdt.core/formatter/org/eclipse/jdt/core/formatter/DefaultCodeFormatterConstants.java#L1182-L1192), where you can read in the latest javadoc:

```java
	 * Note that there is a typo ({@code delcaration} vs. {@code declaration})
	 * in the option name. It has to remain, as fixing it would be a breaking
	 * change.
	 * (...)
	 * @since 3.12
	 */
	public static final String FORMATTER_PARENTHESES_POSITIONS_IN_METHOD_DECLARATION = JavaCore.PLUGIN_ID + ".formatter.parentheses_positions_in_method_delcaration";	//$NON-NLS-1$```
