### ISSUE TITLE
Describe relationship to upstream Eclipse JDT Core in README

### ISSUE THREAD

**Issue by jcrben** [eclipse/aspectj.eclipse.jdt.core#27]
See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/588

**Comment by kriegaex** [comment]
Answered in https://github.com/eclipse-jdt/eclipse.jdt.core/discussions/589#discussioncomment-4362199

**Comment by kriegaex** [comment]
After all AspectJ repositories were moved into their own organisation [eclipse-aspectj](https://github.com/eclipse-aspectj), I managed for the admins to set branch _aspectj_ as the default branch and there committed an updated [read-me file](https://github.com/eclipse-aspectj/eclipse.jdt.core#readme) describing the relationship between Eclipse JDT Core and AspectJ JDT Core.
